["dot_bin/executable_cht"]
    type = "file"
    url = "https://cht.sh/:cht.sh"
    refreshPeriod = "168h"


["dot_bin/executable_tldr"]
    type = "file"
    url = "https://raw.githubusercontent.com/raylee/tldr/master/tldr"
    refreshPeriod = "168h"
