[".local/bin/cht"]
    type = "file"
    url = "https://cht.sh/:cht.sh"
    refreshPeriod = "168h"
    executable = true

[".local/bin/tldr"]
    type = "file"
    url = "https://raw.githubusercontent.com/raylee/tldr/master/tldr"
    refreshPeriod = "168h"
    executable = true

[".antidote"]
    type = "git-repo"
    url = "https://github.com/mattmc3/antidote.git"
    refreshPeriod = "168h"

[".config/NvChad"]
    type = "archive"
    url = "https://github.com/NvChad/NvChad/archive/refs/heads/v2.0.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"
    refreshPeriod = "168h"
