[settings]
experimental = true

[settings.npm]
package_manager = "pnpm"

[tools]
bob = "latest"
node = "lts"
eza = "latest"
starship = "latest"
ripgrep = "latest"
zellij = "latest"
lazygit = "latest"
bat-extras = "latest"
bat = "latest"
difftastic = "latest"
delta = "latest"
fzf = "latest"
zoxide = "latest"
atuin = "latest"

