[settings]
experimental = true

[tools]
bob = "latest"
eza = "latest"
starship = "latest"
ripgrep = "latest"
zellij = "latest"
lazygit = "latest"
bat-extras = "latest"
bat = "latest"
difftastic = "latest"
delta = "latest"
fzf = "latest"
zoxide = "latest"
atuin = "latest"
usage = "latest"
"forgejo:mergiraf/mergiraf" = "latest"
