import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[font]
size = 12.0

[font.bold]
family = "Iosevka Term Curly Slab"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term Curly Slab"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term Curly Slab"
style = "Italic"

[font.normal]
family = "Iosevka Term Curly Slab"
style = "Regular"

[env]
TERM = "xterm-256color"
